### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-html-multiple-pages-T_njfg#1]
@chrisvfritz Can you take a look at this? It's [hosted here](http://furtherfrequencies.surge.sh) and meets the following criteria:

- [x] None of the routes on the website end with `.html`
- [x] A homepage exists, where the purpose of the site is explained
- [x] A "list page" exists that lists your top 3 favorite of this thing (e.g. `/pokemon`) -- each list item should link to the corresponding page for that favorite, detailed below
- [x] For each of your favorites, a page exists to display more information about it (e.g. `/pokemon/bulbasaur`)
- [x] Every page includes links to the homepage and list page (unless either of those are the current page)

Instead of a "list page" I included the list in the navigation bar. I can change this if needed.

**Comment by GriffinMartin** [comment]
@chrisvfritz Updated with complete routes.

**Comment by chrisvfritz** [comment]
Excellent! I love the added `/live` routes. 😄  :shipit:
